apiVersion: apps/v1
kind: Deployment
metadata:
  name: locsearch-deployment
  labels:
    app: locsearch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locsearch
  template:
    metadata:
      labels:
        app: locsearch
    spec:
      containers:
        - name: locsearch
          image: 910681227783.dkr.ecr.eu-west-1.amazonaws.com/locsearch:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"